### ISSUE TITLE
Missing name and host option

### ISSUE THREAD

**Issue by fryfrog** [jimboca/udi-poly-airscape#5]
Hi, I know I had this working at some point... but it isn't anymore. I've tried deleting everything, uninstalling and reinstalling it. When I add it now, there is no option to set the name or hostname of the fan.

https://i.imgur.com/71VrSci.png

What am I doing wrong? Can I just add a "custom option" w/ the right name and value?

**Comment by jimboca** [comment]
Can you hit the download log package from the log page and email that to me? There must be an error on startup.

**Comment by fryfrog** [comment]
I'm still digging, I think my polisy was out of date, did a bunch of `pkg` updating.

**Comment by fryfrog** [comment]
I did a bunch of `pkg update` and `pkg upgrade` and resetting my Polisy to defaults and uninstalling and re-installing and It looks good now. Sorry to have created the issue before digging even further than I already had. :)

**Comment by jimboca** [comment]
No worries, glad you got it sorted!
