### ISSUE TITLE
No module named polyinterface

### ISSUE THREAD

**Issue by fryfrog** [jimboca/udi-poly-airscape#8]
I finally updated my Polisy from FreeBSD 12 -> 13 and Airscape is broken. It was *also* broken on 12, but for Python broken reasons. Any idea?

```
7/2/2021, 13:08:21 [polyglot] error: NSChild STDERR: Airscape: Traceback (most recent call last):
  File "./airscape-poly.py", line 5, in <module>
    import polyinterface
ModuleNotFoundError: No module named 'polyinterface'
```

**Comment by fryfrog** [comment]
I think I had to install py38-pip and maybe pip install polyinterface? It is working now though! :)

**Comment by jimboca** [comment]
Nice, glad you figured it out so quickly!
